// 架電結果の種別
export type CallResultType =
  | '架電済'
  | '通電'
  | 'アポ獲得'
  | '不在'
  | '拒否'
  | 'その他';

// 架電結果の詳細情報
export interface CallResult {
  id: string;
  callId: string;
  resultType: CallResultType;
  notes: string;
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

// 活動種別
export type ActivityType =
  | 'call'
  | 'visit'
  | 'meeting'
  | 'estimate'
  | 'order'
  | 'other';

// 活動ステータス
export type ActivityStatus = 'completed' | 'scheduled' | 'cancelled';

// 活動履歴
export interface ActivityHistory {
  id: string;
  companyId: string;
  contactId?: string;
  userId: string;
  activityType: ActivityType;
  activityDate: string;
  summary: string;
  details?: string;
  status: ActivityStatus;
  relatedCallId?: string;
  relatedVisitId?: string;
  relatedNegotiationId?: string;
}

// BANTC情報
export interface BANTCInfo {
  id: string;
  contactId: string;
  companyId: string;
  budget: {
    range?: string;
    amount?: number;
    period?: string;
    notes?: string;
  };
  authority: {
    level?: 'high' | 'medium' | 'low';
    title?: string;
    decisionProcess?: string;
    notes?: string;
  };
  need: {
    urgency?: 'high' | 'medium' | 'low';
    painPoints?: string[];
    requirements?: string[];
    notes?: string;
  };
  timeline: {
    targetDate?: string;
    phase?: string;
    constraints?: string[];
    notes?: string;
  };
  competition: {
    competitors?: string[];
    currentSolution?: string;
    switchingCost?: string;
    notes?: string;
  };
  aiGenerated: boolean;
  humanVerified: boolean;
  updatedAt: string;
}

// 架電情報の拡張（既存のCallItemを拡張）
export interface CallItemExtended {
  id: string;
  companyName: string;
  contactPerson: string;
  phoneNumber: string;
  priority: 'high' | 'medium' | 'low';
  lastContactDate: string;
  industry: string;
  status: 'new' | 'negotiating' | 'proposal' | 'closed';
  purchasedProducts: string[];
  industryTrends: string[];
  keyPersons: {
    name: string;
    position: string;
    notes: string;
  }[];
  notes: string;
  // 新規追加フィールド
  callResults?: CallResult[];
  activityHistory?: ActivityHistory[];
  bantcInfo?: BANTCInfo;
}
